package com.sherchen.heartrate.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


import com.sherchen.heartrate.greendao.HistoryEntity;
import com.sherchen.heartrate.greendao.HistoryEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig historyEntityDaoConfig;

    private final HistoryEntityDao historyEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        historyEntityDaoConfig = daoConfigMap.get(HistoryEntityDao.class).clone();
        historyEntityDaoConfig.initIdentityScope(type);

        historyEntityDao = new HistoryEntityDao(historyEntityDaoConfig, this);

        registerDao(HistoryEntity.class, historyEntityDao);
    }
    
    public void clear() {
        historyEntityDaoConfig.getIdentityScope().clear();
    }

    public HistoryEntityDao getHistoryEntityDao() {
        return historyEntityDao;
    }

}
